<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307082141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE machine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_memory INT NOT NULL, total_cpu INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE process (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, memory INT NOT NULL, cpu INT NOT NULL, machine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_861D1896F6B75B26 ON process (machine_id)');
        $this->addSql('ALTER TABLE process ADD CONSTRAINT FK_861D1896F6B75B26 FOREIGN KEY (machine_id) REFERENCES machine (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE process DROP CONSTRAINT FK_861D1896F6B75B26');
        $this->addSql('DROP TABLE machine');
        $this->addSql('DROP TABLE process');
    }
}
